# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/extras/Build/CMake/JUCEConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/extras/Build/CMake/JUCEHelperTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/extras/Build/CMake/JUCEUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/extras/Build/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/extras/Build/juceaide/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/JUCE/modules/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/xcode_build/JUCE/tools/JUCEToolsExport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/BasicConfigVersion-ExactVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kazumawatanabe/3d-guitar-amp-renderer/xcode_build/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/kazumawatanabe/3d-guitar-amp-renderer/xcode_build/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -P /Users/kazumawatanabe/3d-guitar-amp-renderer/xcode_build/CMakeFiles/VerifyGlobs.cmake

/Users/kazumawatanabe/3d-guitar-amp-renderer/xcode_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -H/Users/kazumawatanabe/3d-guitar-amp-renderer -B/Users/kazumawatanabe/3d-guitar-amp-renderer/xcode_build
